# for use in skaffold build/deploy

FROM node:lts-alpine
EXPOSE 5001

RUN apk update && apk add --no-cache supervisor
COPY supervisord-devmode.conf /etc/supervisord.conf
RUN mkdir /var/run/supervisord

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY package.json .
COPY package-lock.json .
RUN npm ci
COPY *js /opt/app/
COPY assets /opt/app/assets
COPY templates /opt/app/templates
COPY src /opt/app/src

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
