version: '3'

services:
    postgres_keycloak:
        image: postgres
        volumes:
          - postgres_keycloak_data:/var/lib/postgresql/data
        environment:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
    keycloak:
        build:
            context: ./keycloak
            dockerfile: Dockerfile-keycloak
        command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING
        environment:
          DB_VENDOR: POSTGRES
          DB_ADDR: postgres_keycloak
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_PASSWORD: keycloak
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          KEYCLOAK_LOGLEVEL: WARN
          ROOT_LOGLEVEL: WARN
        ports:
          - 8888:8080
        depends_on:
          - postgres_keycloak
volumes:
    postgres_keycloak_data:
