{{ if .Values.minio.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.pvc.size }}
{{ end }}
