{{ if .Values.rabbit.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      name: rabbit
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.7-management
          resources:
            requests:
              cpu: 100m
              memory: "200M"
            limits:
              cpu: 250m
              memory: "400M"
          ports:
            - name: amqp
              containerPort: 5672
            - name: admin
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials
                  key: password
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/tracks"
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbit log_levels [{connection,error}]"
  selector:
    matchLabels:
      app: rabbit
  {{ end }}
