apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: envoy
  annotations:
    # this needs to be 'public', not 'nginx', for newer versions of mk8s
    # kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tracks{{ .Values.hostSuffix }}{{ .Values.domainSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: envoy
              servicePort: 10000

