{{ if .Values.keycloak.deploy }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations: {}
    # this needs to be 'public', not 'nginx', for newer versions of mk8s
    # kubernetes.io/ingress.class: public
spec:
  rules:
    - host: keycloak{{ .Values.hostSuffix }}{{ .Values.domainSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: keycloak
              servicePort: 8080
{{ end }}
