{{ if .Values.keycloak.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  selector:
    app: postgres-keycloak
  ports:
    - port: 5432
      targetPort: 5432
{{ end }}
