# domain for created ingresses
domainSuffix: .iron.mapleleaf.intranet
# domainSuffix: .fvgke.mapleleafsoftware.io

hostSuffix: ""
environment: localdev

keycloak:
  useExternal: true
  externalUrl: "http://keycloak.mapleleaf.intranet:8080/auth"

frontend:
  image: frontend:latest
backend:
  image: backend:latest
migrator:
  image: migrator:latest
gpx_intake_processor:
  image: gpx_intake_processor:latest
database:
  pvc:
    size: "5Gi"
minio:
  pvc:
    size: "1Gi"
