domainSuffix: .local
hostSuffix: ""
environment: localdev

ingress:
  useTLS: true

config:
  jwksUrl: http://keycloak:8080/auth/realms/tracks-dev/protocol/openid-connect/certs
  keycloakBaseUrl: http://keycloak:8080
  keycloakSASecret: "f8cdbacd-5d5d-4149-a682-b17a3f2f4b1d"

keycloak:
  deploy: true
  useExternal: false
  externalUrl: "" # eg "http://keycloak/auth"
database:
  deploy: true
  pvc:
    size: "5Gi"
rabbit:
  deploy: true
minio:
  deploy: true
  pvc:
    size: "1Gi"
frontend:
  image: frontend:latest
backend:
  image: backend:latest
migrator:
  image: migrator:latest
gpx_intake_processor:
  image: gpx_intake_processor:latest
export_processor:
  image: export_processor:latest
