apiVersion: skaffold/v2beta13
kind: Config
build:
  local:
    concurrency: 0
  artifacts:
    - image: frontend
      context: ../frontend
      docker:
        dockerfile: Dockerfile
    - image: backend
      context: ../backend
      docker:
        dockerfile: Dockerfile
    - image: migrator
      context: ../migrations
      docker:
        dockerfile: Dockerfile
    - image: gpx_intake_processor
      context: ../gpx_intake_processor
      docker:
        dockerfile: Dockerfile
    - image: export_processor
      context: ../export_processor
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: skaffold-helm-release
        chartPath: ./charts/tracks
        setValueTemplates:
          domainSuffix: .local
          rabbit.deploy: false
          keycloak.deploy: true
        artifactOverrides:
          frontend:
            image: frontend
          backend:
            image: backend
          migrator:
            image: migrator
          gpx_intake_processor:
            image: gpx_intake_processor
          export_processor:
            image: export_processor
profiles:
  - name: kanikoBuild
    build:
      tagPolicy:
        dateTime: { }
      cluster:
        concurrency: 4
        # pullSecretName: kaniko-secret
        resources:
          requests:
            cpu: 1
            ephemeralStorage: 2Gi
            memory: 2Gi
          limits:
            cpu: 2
            ephemeralStorage: 2Gi
            memory: 4Gi
      artifacts:
        - image: frontend
          context: ../frontend
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: backend
          context: ../backend
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: migrator
          context: ../migrations
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: gpx_intake_processor
          context: ../gpx_intake_processor
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: export_processor
          context: ../export_processor
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
