apiVersion: skaffold/v2beta13
kind: Config
build:
  local:
    concurrency: 0
  artifacts:
    - image: frontend
      context: ../frontend
      sync:
        manual:
        - src: '**/*.ts'
          dest: '/opt/app'
        - src: '**/*.tsx'
          dest: '/opt/app'
        - src: '**/*.scss'
          dest: '/opt/app'
      docker:
        dockerfile: Dockerfile-devmode
    - image: backend
      context: ../backend
      sync:
        manual:
          - src: '**/*.ts'
            dest: '/opt/app'
      docker:
        dockerfile: Dockerfile
    - image: migrator
      context: ../migrations
      docker:
        dockerfile: Dockerfile
    - image: gpx_intake_processor
      context: ../gpx_intake_processor
      docker:
        dockerfile: Dockerfile
    - image: export_processor
      context: ../export_processor
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: skaffold-helm-release
        chartPath: ./charts/tracks
        setValueTemplates:
          domainSuffix: .iron.mapleleaf.intranet
          rabbit.deploy: false
          keycloak.deploy: true
        artifactOverrides:
          frontend:
            image: frontend
          backend:
            image: backend
          migrator:
            image: migrator
          gpx_intake_processor:
            image: gpx_intake_processor
          export_processor:
            image: export_processor
profiles:
  - name: kanikoBuild
    build:
      tagPolicy:
        dateTime: { }
      cluster:
        verbosity: debug
        image: gcr.io/kaniko-project/executor:v1.5.0-slim
        dockerConfig:
          secretName: mapleleaf-registry-opaque
        concurrency: 1
        resources:
          requests:
            cpu: 1
            ephemeralStorage: 2Gi
            memory: 2Gi
          limits:
            cpu: 4
            ephemeralStorage: 2Gi
            memory: 4Gi
      artifacts:
        - image: frontend
          context: ../frontend
          sync:
            manual:
              - src: '**/*.ts'
                dest: '/opt/app'
              - src: '**/*.tsx'
                dest: '/opt/app'
              - src: '**/*.scss'
                dest: '/opt/app'
          kaniko:
            dockerfile: Dockerfile-devmode
            cache:
              repo: ""
        - image: backend
          context: ../backend
          sync:
            manual:
              - src: '**/*.ts'
                dest: '/opt/app'
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: migrator
          context: ../migrations
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: gpx_intake_processor
          context: ../gpx_intake_processor
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
        - image: export_processor
          context: ../export_processor
          kaniko:
            dockerfile: Dockerfile
            cache:
              repo: ""
