apiVersion: skaffold/v2beta13
kind: Config
build:
  cluster:
    concurrency: 1
    # pullSecretName: kaniko-secret
    resources:
      requests:
        cpu: 1
        ephemeralStorage: 2Gi
        memory: 2Gi
      limits:
        cpu: 2
        ephemeralStorage: 2Gi
        memory: 4Gi
  artifacts:
  - image: frontend
    context: ../frontend
    kaniko:
      dockerfile: Dockerfile
      cache:
        repo: ""
  - image: backend
    context: ../backend
    kaniko:
      dockerfile: Dockerfile
      cache:
        repo: ""
  - image: migrator
    context: ../migrations
    kaniko:
      dockerfile: Dockerfile
      cache:
        repo: ""
  - image: gpx_intake_processor
    context: ../gpx_intake_processor
    kaniko:
      dockerfile: Dockerfile
      cache:
        repo: ""
  - image: export_processor
    context: ../export_processor
    kaniko:
      dockerfile: Dockerfile
      cache:
        repo: ""
deploy:
  helm:
    releases:
      - name: skaffold-helm-release
        chartPath: ./charts/tracks
        artifactOverrides:
          frontend:
            image: frontend
          backend:
            image: backend
          migrator:
            image: migrator
          gpx_intake_processor:
            image: gpx_intake_processor
          export_processor:
            image: export_processor
